# Matrix Generation and Indexing in MATLAB

A matrix is a two-dimensional array consisting of $m$ rows and $n$ columns. Matrices are the basic elements in MATLAB. 

Learning objectives:
 - Entering a matrix
 - The colon operator
 - Indexing into a matrix
 - Creating a submatrix
 - Deleting rows/columns
 - Matrix and array operations

## Entering a vector

A vector is a special case of a matrix. An array of dimension $1 \times n$ is called a *row vector*, whereas an array of dimension $m \times 1$ is called a *column vector*. The elements of vectors in MATLAB are enclosed by square brackets and are separated by spaces or by commas. For example, to enter a row vector, $v$:

In [1]:
v = [1 4 7 10 13]

v =

    1    4    7   10   13



Column vectors are created in a similar way, however, semicolon ';' must separate the
components of a column vector:

In [2]:
w = [1; 4; 7; 10; 13]

w =

    1
    4
    7
   10
   13



A row vector is converted to a column vector using the *transpose operator*, is denoted by an apostrophe or a single quote (’).

In [3]:
w = v'

w =

    1
    4
    7
   10
   13



We can use parentheses to access the values in a vector:

In [4]:
w(1), w(2)

ans =  1
ans =  4


Note that the indices in MATLAB start from 1, unlike Python, in which indices start from 0.

## The colon operator

The colon operator will prove very useful and understanding how it works is the key to efficient and convenient usage of MATLAB. It occurs in several different forms.

Often we must deal with matrices or vectors that are too large to enter one element at a time. For example, suppose we want to enter a vector x consisting of points (0, 0.1, 0.2, 0.3, · · · , 5). We can use the command

In [5]:
x = 0:0.1:5;
size(x)

ans =

    1   51



This produces a row vector with 51 elements.

If the mid-value is omitted, then it is treated as 1.

In [6]:
x = 5:-1:0

x =

   5   4   3   2   1   0



The colon operator is very useful in indexing arrays.

In [7]:
v(1:3)

ans =

   1   4   7



The number before ':' is the first index to extract, and the number after ':' is the last index to extract. This is different from the semantics of the `range` function in Python.

All elements from the third through the last elements:

In [8]:
w(3:end)

ans =

    7
   10
   13



where `end` signifies the last element in the vector. Note that

In [9]:
v(1:end)

ans =

    1    4    7   10   13



produces a row vector (since $v$ is a row vector). However,

In [10]:
v(:)

ans =

    1
    4
    7
   10
   13



always produces a column vector, regardless whether $v$ is a row or column vector.

## Entering a matrix

A matrix is a two-dimensional array of numbers. To type a matrix into MATLAB you must
 - begin with a square bracket, '['
 - separate elements in a row with spaces or commas ','
 - use a semicolon ';' to separate rows
 - end the matrix with another square bracket ']'.
 
For example, to enter a matrix 
$A = \left[\begin{array}{ccc}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}\right]:$

In [11]:
A = [1 2 3; 4 5 6; 7 8 9]

A =

   1   2   3
   4   5   6
   7   8   9



## Matrix indexing

The element of row $i$ and column $j$ of the matrix $A$ is denoted by A(i,j). For example,

In [12]:
A(2,1)

ans =  4


We can also modify the value of an entry through index. For example,

In [13]:
A(3,3) = 0;
A

A =

   1   2   3
   4   5   6
   7   8   0



A matrix can also be indexed using a single index. In this case, the matrix is treated as one-dimensional array, mapped from the 2-D array in a column-by-column manner.

In [14]:
A(4)

ans =  2


## Creating a sub-matrix

To extract a `submatrix` B consisting of rows 2 and 3 and columns 1 and 2 of the matrix $A$, do the following:

In [15]:
B = A([2 3],[1 2])

B =

   4   5
   7   8



The colon operator is also useful to create a sub-matrix. The statement A($a:b,c:d$) specifies rows $a$ to $b$ and column $c$ to $d$. Subscript expressions refer to portions of a matrix. 

As a special case, a colon (:) as the row or column specifier covers all the entries in that row or column; thus
 - A(:,$j$) is the $j$th column of A, while 
 - A($i$,:) is the $i$th row, and
 - A(end,:) picks out the last row of A.

For example,

In [16]:
A(2,:)

ans =

   4   5   6



is the second row elements of $A$.

In [17]:
 A(:,2:3)

ans =

   2   3
   5   6
   8   0



extracts a sub-matrix with the last two columns of A.

Note that the assignment of sub-matrix creates a separate matrix from A.

In [18]:
B = A([2 3],[1 2]);
B(1,1) = -1;
A(2,1)

ans =  4


B and A have different memory. Changing B does not change A. 

Note that in Python, the slicing into an array behaves differently.

A(:) converts A into a column vector in a column-by-column manner.

In [19]:
reshape(A, 1, 9)

ans =

   1   4   7   2   5   8   3   6   0



## Deleting a row or column

A row or a column of a matrix can be deleted by setting it to a null vector, []. For example,

In [20]:
B = A;
B(2, :)=[];
B

B =

   1   2   3
   7   8   0



## Dimension of matrices

To determine the *dimensions* of a matrix or vector, use the command `size`. For example,

In [21]:
size(A)

ans =

   3   3



or explicitly

In [22]:
[m,n]=size(A)

m =  3
n =  3


We can obtain the numbers of rows and columns by specifying a second argument:

In [23]:
size(B, 1)
size(B, 2)

ans =  2
ans =  3


Another way to create a matrix is to use a function, such as `ones`, `zeros`, or `rand`. For example, create a 5-by-1 column vector of `zeros`.

In [24]:
z = zeros(5,1)

z =

   0
   0
   0
   0
   0



## Matrix and array operations

MATLAB allows you to process all of the values in a matrix using a single arithmetic operator or function.

In [25]:
A + 10

ans =

   11   12   13
   14   15   16
   17   18   10



In [26]:
sin(A)

ans =

   0.84147   0.90930   0.14112
  -0.75680  -0.95892  -0.27942
   0.65699   0.98936   0.00000



To transpose a matrix, use a single quote ('):

In [27]:
A'

ans =

   1   4   7
   2   5   8
   3   6   0



You can perform standard matrix multiplication, which computes the inner products between rows and columns, using the * operator. For example, confirm that a matrix times its inverse returns the identity matrix:

In [28]:
P = A * inv(A)

P =

   1.0000e+00   5.5511e-17  -4.1633e-17
   5.5511e-17   1.0000e+00  -8.3267e-17
   1.7764e-15  -8.8818e-16   1.0000e+00



Notice that p is not a matrix of integer values. MATLAB stores numbers as floating-point values, and arithmetic operations are sensitive to small differences between the actual value and its floating-point representation. You can display more decimal digits using the format command:

In [29]:
format short
P = A * inv(A)

P =

   1.0000e+00   5.5511e-17  -4.1633e-17
   5.5511e-17   1.0000e+00  -8.3267e-17
   1.7764e-15  -8.8818e-16   1.0000e+00



Reset the display to the shorter format using

format short

format affects only the display of numbers, not the way MATLAB computes or saves them.

To perform element-wise multiplication rather than matrix multiplication, use the .* operator:

In [30]:
P = A .* A

P =

    1    4    9
   16   25   36
   49   64    0



## Concatenating matrices

Concatenation is the process of joining arrays to make larger ones. In fact, you made your first array by concatenating its individual elements. The pair of square brackets [ ] is the concatenation operator.

Concatenating arrays next to one another using commas is called *horizontal* concatenation. Each array must have the same number of rows. Similarly, when the arrays have the same number of columns, you can concatenate *vertically* using semicolons.

In [31]:
C = [A, A]

C =

   1   2   3   1   2   3
   4   5   6   4   5   6
   7   8   0   7   8   0



In [32]:
D = [A; A]

D =

   1   2   3
   4   5   6
   7   8   0
   1   2   3
   4   5   6
   7   8   0



In [33]:
diag(A)

ans =

   1
   5
   0



## Matrix generators

MATLAB provides functions that generates elementary matrices. The matrix of zeros, the matrix of ones, and the identity matrix are returned by the functions zeros, ones, and eye, respectively.

<table>
<center><b>Elementary matrices</b></center>
    <tr>
<td> eye(m,n) </td>
<td> Returns an m-by-n matrix with 1 on the main diagonal </td>
    </tr>
    <tr>
<td> eye(n) </td>
<td> Returns an n-by-n square identity matrix </td>
    </tr>
    <tr>
<td> zeros(m,n) </td>
<td> Returns an m-by-n matrix of zeros </td>
    </tr>
    <tr>
<td> ones(m,n) </td>
<td> Returns an m-by-n matrix of ones </td>
    </tr>
    <tr>
<td> diag(A) </td>
<td> Extracts the diagonal of matrix A </td>
    </tr>
    <tr>
<td> rand(m,n) </td>
<td> Returns an m-by-n matrix of random numbers with uniform distribution </td>
    </tr>
    <tr>
<td> randn(m,n) </td>
<td> Returns an m-by-n matrix of random numbers with normal distribution </td>
    </tr>
</table>

For example:

In [34]:
b = ones(3,1)

b =

   1
   1
   1



which is equivalent to b=[1;1;1].

In [35]:
eye(3)

ans =

Diagonal Matrix

   1   0   0
   0   1   0
   0   0   1



In [36]:
C = [1 2; 3 4];
D = [C zeros(2); ones(2) eye(2)]

D =

   1   2   0   0
   3   4   0   0
   1   1   1   0
   1   1   0   1



generates a 3-by-3 identity matrix.

Acknowledgment: The material in this Notebook was adapted from Section 2.5 of "Introduction to MATLAB for Engineering Students" by David Houcque, Northwestern University, 2004, as well as the MATLAB Primer of MathWorks.